Implement the functional tests for the builder app
snu-quiqcl/iquip pull request #105
Opened 2023-08-11 19:48 UTC by BECATRUE

This PR will close #87.

I implemented the left unit tests and functional tests.
Now, the coverage rate has reached 100%.
<img width="70%" src="https://github.com/snu-quiqcl/iquip/assets/76851886/4281197f-1e23-42df-99c5-e52d64a0b23c">

2023-08-16 02:11 UTC, kangz12345 requested changes

2023-08-16 02:11 UTC, kangz12345 commented on tests/test_builder.py
> +        "arg7": [{"ty": "NumberValue", "default": "default3"}, None, None]
Not a big deal but why don't you change the `default` indices as well? (`"default4"`, etc.)

2023-08-16 02:11 UTC, kangz12345 commented on tests/test_builder.py
> +        self.assertEqual(str(cm.exception), msg)
I think checking the error message is too "tight" and not scalable.
If we want to check specific errors, I think we should define error codes.
However, for this, just checking `ValueError` would be enough.

2023-08-16 02:11 UTC, kangz12345 commented on tests/test_builder.py
> +            ("name1", {"choices": ["value1", "value2", "value3"], "default": "value2"}, "value2"),
I don't remember: what happens if `"default"` is not in `"choices"`?

2023-08-16 02:11 UTC, kangz12345 commented on tests/test_builder.py
> +    def test_init(self):
This is testing just the spinbox min/max values, so the name `test_init()` seems too broad.
How about change it to, e.g. `test_spinbox()`?
You can test `decimals()` as well.

2023-08-16 02:11 UTC, kangz12345 commented on tests/test_builder.py
> +        argInfo1 = {"unit": "us", "scale": 1e-6, "step": 1e-7, "min": 10 * 1e-6, "max": 100 * 1e-6,
I think `10e-6` is more readable than `10 * 1e-6`.

2023-08-16 02:11 UTC, kangz12345 commented on tests/test_builder.py
> +        with mock.patch("iquip.apps.builder.compute_scale") as mocked_compute_scale:
How about not mocking it since this is a functional test?

2023-08-16 02:11 UTC, kangz12345 commented on tests/test_builder.py
> +                self.assertEqual(entry.warningLabel.text(), warningLabelText)
How about checking if the label text is empty or not, instead of matching the full text?

2023-08-16 02:11 UTC, kangz12345 commented on tests/test_builder.py
> +            logger = logging.getLogger()
How about designating the source logger directly: `"iquip.apps.builder"`?

2023-08-17 16:50 UTC, BECATRUE commented on tests/test_builder.py
> +        "arg7": [{"ty": "NumberValue", "default": "default3"}, None, None]
I didn't even think of that😅 I will update it.

2023-08-17 16:52 UTC, BECATRUE commented on tests/test_builder.py
> +        self.assertEqual(str(cm.exception), msg)
Okay, then I will remove the part checking the detailed message.

2023-08-17 16:56 UTC, BECATRUE commented on tests/test_builder.py
> +            ("name1", {"choices": ["value1", "value2", "value3"], "default": "value2"}, "value2"),
When fetching the experiment arguments information, the artiq-master makes an error as follows:
![image](https://github.com/snu-quiqcl/iquip/assets/76851886/0e1a6281-ee38-4c87-84e8-6be8b9980f54)

Thus, the proxy server returns a 500 Internal Server Error.

2023-08-17 17:20 UTC, BECATRUE commented on tests/test_builder.py
> +    def test_init(self):
I agree with you! Also, I will add tests about `decimals()`.

2023-08-17 17:27 UTC, BECATRUE commented on tests/test_builder.py
> +        with mock.patch("iquip.apps.builder.compute_scale") as mocked_compute_scale:
It looks more appropriate!

2023-08-17 17:28 UTC, BECATRUE commented on tests/test_builder.py
> +                self.assertEqual(entry.warningLabel.text(), warningLabelText)
Similar to the review above, I will only test whether or not.

2023-08-19 15:47 UTC, kangz12345 commented on tests/test_builder.py
> +            ("name1", {"choices": ["value1", "value2", "value3"], "default": "value2"}, "value2"),
Thank you for the explanation. Then does the builder app handle such errors?

2023-08-21 04:03 UTC, BECATRUE commented on tests/test_builder.py
> +            ("name1", {"choices": ["value1", "value2", "value3"], "default": "value2"}, "value2"),
The error occurs when fetching the experiment info, thus it is handled in `explorer.py`.

If an Internal Server Error is received, this [`try`](https://github.com/snu-quiqcl/iquip/blob/develop/iquip/apps/thread.py#L60) statement catches the exception.

2023-08-21 05:51 UTC, kangz12345 commented on tests/test_builder.py
> +            ("name1", {"choices": ["value1", "value2", "value3"], "default": "value2"}, "value2"),
Oh I see. Thank you!

2023-08-21 05:52 UTC, kangz12345 approved these changes
LGTM

2023-08-24 05:47 UTC, BECATRUE commented
Could you check this PR? @Aijuh

2023-08-25 03:27 UTC, Aijuh approved these changes
LGTM

2023-08-30 05:55 UTC, merged