`NDArrayViewer` and `CurvePlotViewer`
snu-quiqcl/iquip pull request #125
Opened 2023-09-12 10:07 UTC by kangz12345

This PR include a new module `iquip.apps.dataviewer` which contains `NDArrayViewer` and `CurvePlotViewer`.
It also introduces a new dataclass `AxisInfo`.

The basic idea for plotting an ndarray:
1. We are interested in target measurement data, e.g., photon counts.
2. We perform "scan" experiment, e.g., repeat 200shots and scan time, frequency, etc.
3. Each scanning parameter (shot, time, frequency, etc.) adds 1 dimension to the resulting ndarray.
4. To plot it, we need information for each axis, i.e., scanning parameter. `AxisInfo` represents this information.

As an example, I provide another branch: `kangz12345/122/ndarrayviewer-demo`.
It includes a plot widget and a push button.
If you click the button, it will randomly generate a 4-sequence sampled in {1, 2, 3}.
Then it multiplies `1e-3` to make its scale to m-.
The left (vertical) axis is labeled by "Voltage" with unit "V" (however, `pyqtgraph` automatically displays the unit as "mV" since the values are in that scale).
`AxisInfo` contains the scanning parameter information, which is time.

For our usual cases, we need to preprocess the data to make it a 1D array to use `CurvePlotViewer`. I will develop this in the next PRs.

NOTE: I will implement several features WITHOUT unit tests for few weeks, because we need such features as soon as possible. I will implement unit tests later, after finishing mandatory implementations.

This closes #122.

2023-09-12 18:10 UTC, BECATRUE requested changes

2023-09-12 18:10 UTC, BECATRUE commented on iquip/apps/dataviewer.py
> +            data: The new ndarray data. Its dimension should be self.dim.
`self.ndim`!

2023-09-12 18:10 UTC, BECATRUE commented on iquip/apps/dataviewer.py
> +        """
It looks better to add "Extended", right?

2023-09-12 22:58 UTC, kangz12345 commented on iquip/apps/dataviewer.py
> +        """
I'm not sure 😄 actually it is overwritten, rather than overridden or extended.
Note that its arguments are different from its super's.

2023-09-13 05:08 UTC, kangz12345 commented
@BECATRUE Please check this out!

2023-09-13 05:45 UTC, BECATRUE approved these changes
LGTM!

2023-09-13 05:59 UTC, merged