Frame with all TTL controllers: `TTLControllerFrame`
snu-quiqcl/iquip pull request #158
Opened 2023-09-20 08:41 UTC by BECATRUE

This closes #154.

For test, store the following code in the repository path.
```python
from PyQt5.QtWidgets import QApplication

from iquip.apps.monitor import TTLControllerFrame

qapp = QApplication([])
widget = TTLControllerFrame({
    "AAA": 0, "BBB": 1, "CCC": 2, "DDD": 3,
    "EEE": 4, "FFF": 5, "GGG": 6, "HHH": 7
})
widget.show()
qapp.exec_()
```

### Result
<img width="50%" src="https://github.com/snu-quiqcl/iquip/assets/76851886/ad8fd4c9-1601-4193-ba96-e23afac99215">

2023-09-20 10:17 UTC, kangz12345 requested changes

2023-09-20 10:17 UTC, kangz12345 commented on iquip/apps/monitor.py
> +    NUM_COLUMNS = 4
I think this should be an instance (constant) attribute, instead of class constant. Imagine we want several Frames and their number of columns different.

2023-09-20 10:17 UTC, kangz12345 commented on iquip/apps/monitor.py
> +        self.overrideButton = QPushButton("Not Overridden", self)
How about "Not Overriding"? I think "overriding" is more intuitive since it is overriding the ttl level.

2023-09-20 16:40 UTC, BECATRUE commented on iquip/apps/monitor.py
> +    NUM_COLUMNS = 4
I see. Then I'll make sure to transfer the number of columns to an argument of constructor.

2023-09-20 16:45 UTC, BECATRUE commented on iquip/apps/monitor.py
> +    NUM_COLUMNS = 4
Later we may change the number of columns, but I won't save it as an attribute because we only need it in the contructor right now.

2023-09-21 01:31 UTC, kangz12345 approved these changes
LGTM!

2023-09-21 01:32 UTC, merged