Scheduler: Construct the model/view architecture
snu-quiqcl/iquip pull request #184
Opened 2023-10-05 05:42 UTC by BECATRUE

This closes #182.

As the first step of a new scheduler, I constructed the basic model/view architecture.
For test, I just set scheduled queue directly in temporary.

### Screenshot
![image](https://github.com/snu-quiqcl/iquip/assets/76851886/4fb0ae77-46d5-456d-ae99-7533036a76b9)

2023-10-05 08:24 UTC, kangz12345 requested changes

2023-10-05 08:24 UTC, kangz12345 commented on iquip/apps/scheduler.py
> +        DisplayRole: Returns column-th info field of row-th experiment in scheduleList.
Please start the return value section with `"Returns:"` just like the others.

2023-10-05 08:24 UTC, kangz12345 commented on iquip/apps/scheduler.py
> +            return QVariant()
Will these be updated later? If not, combining them would be better using `or`.

2023-10-05 08:24 UTC, kangz12345 commented on iquip/apps/scheduler.py
> +        Vertical: Returns an index started from 1.
Please follow the return value docstring style.

2023-10-05 09:13 UTC, BECATRUE commented on iquip/apps/scheduler.py
> +            return QVariant()
It will be updated later, but it may be a far futere. So, I will combine them.

2023-10-06 01:09 UTC, kangz12345 approved these changes
LGTM

2023-10-06 05:37 UTC, merged