Improve thread signals and slots
snu-quiqcl/iquip pull request #214
Opened 2023-10-23 04:33 UTC by kangz12345

This closes #213.

Since this has many changes (not just additions), it must be tested and reviewed thoroughly.
I will test it on the lab PC.

2023-10-23 06:19 UTC, BECATRUE requested changes

2023-10-23 06:19 UTC, BECATRUE commented on iquip/apps/builder.py
>              experimentPath, experimentArgs, schedOpts, ip, port: See the attributes section.
Now, it is okay to write only "See the attributes section.".

2023-10-23 06:19 UTC, BECATRUE commented on iquip/apps/explorer.py
> +        self.fileFinderThread.finished.connect(self.fileFinderThread.deleteLater)
Please update `_FileFinderThread` call, and connect `fetched` signal to `self._addFile()`.

2023-10-24 09:13 UTC, kangz12345 commented
I tested the branch on the lab PC.

2023-10-25 04:17 UTC, BECATRUE approved these changes
LGTM!

2023-10-25 04:24 UTC, merged