Fetch RID list in remote part
snu-quiqcl/iquip pull request #262
Opened 2024-03-25 12:21 UTC by BECATRUE

This is a part of #258.

What I have implemented is:
- Add widgets to select a target date and hour.
- Once any is changed, fetch the corresponding RID list.
- Reconstruct signals in dataviewer app.

![image](https://github.com/snu-quiqcl/iquip/assets/76851886/13382708-b3c9-4176-9c80-afa609bd5f8f)

The figure means that RIDs executed today are 765 to 769.

2024-03-26 17:21 UTC, kangz12345 requested changes
The way of getting the realtime part and remote part looks so weird... Sorry for the messy design 😄 Let's modify that later.

2024-03-26 17:21 UTC, kangz12345 commented on iquip/apps/dataviewer.py
> +        dateHourChanged(date, hour): The target date and hour are changed. If the hour is not set,
Let's clarify that the date is in the ISO format.

2024-03-26 17:21 UTC, kangz12345 commented on iquip/apps/dataviewer.py
> +        dateHourChanged(date, hour): The target date and hour are changed. If the hour is not set,
Also, it does not give any hint about the type of `hour` when it is set.

2024-03-26 17:21 UTC, kangz12345 commented on iquip/apps/dataviewer.py
> +        self.hourCheckBox.stateChanged.connect(self.enableHourSpinBox)
How about using `clicked(checked)` signal and connect `self.hourComboBox.setEnabled` as its slot? `QCheckBox` inherits `QAbstractButton`, but I'm not sure you can use `clicked` signal.

2024-03-26 17:21 UTC, kangz12345 commented on iquip/apps/dataviewer.py
> +    def enableHourSpinBox(self, state: int):
In this case, the method name should be `setEnabled...`.

2024-03-26 17:21 UTC, kangz12345 commented on iquip/apps/dataviewer.py
> +            self.websocket.close()
Is this thread-safe?

2024-03-27 07:36 UTC, BECATRUE commented on iquip/apps/dataviewer.py
> +            self.websocket.close()
Umm.. I think it is thread-safe as this method is located in `QThread`.
However I'm not sure about this..

2024-03-27 07:50 UTC, BECATRUE commented on iquip/apps/dataviewer.py
> +        self.hourCheckBox.stateChanged.connect(self.enableHourSpinBox)
Wow, it works well! I'll do that.

2024-03-27 07:54 UTC, BECATRUE commented on iquip/apps/dataviewer.py
> +    def enableHourSpinBox(self, state: int):
I used `clicked` signal instaed of `stateChanged` signal, so now this method becomes unusable.

2024-03-27 07:55 UTC, kangz12345 commented on iquip/apps/dataviewer.py
> +            self.websocket.close()
I mean while the `QThread` is communicating with the artiq proxy using `self.websocket`, someone can call `stop()` in another thread.
Then the `websocket` object must support the thread-safe API.
Several different thread can use the `websocket` instance in this code.

2024-03-27 08:14 UTC, BECATRUE commented on iquip/apps/dataviewer.py
> +            self.websocket.close()
I see.

According to [docs](https://websockets.readthedocs.io/en/stable/reference/sync/client.html#websockets.sync.client.ClientConnection.close), `close()` waits for all incoming messages to be read with `recv()`, so it looks thread-safe.

And I can't say for sure, but looking at the code of `websocket`, it uses `threading.Lock()` for guaranteeing thread-safety.

2024-04-01 14:37 UTC, kangz12345 commented on iquip/apps/dataviewer.py
> +            self.websocket.close()
Okay, then maybe it is thread-safe!

2024-04-02 16:57 UTC, kangz12345 approved these changes
LGTM

2024-04-03 07:50 UTC, merged