Restart synchronizing TTL status when the connection is lost
snu-quiqcl/iquip pull request #268
Opened 2024-04-01 08:28 UTC by BECATRUE

This closes #263.

Now, ARTIQ is in use, so I cannot test this PR..

2024-04-01 12:23 UTC, kangz12345 requested changes

2024-04-01 12:23 UTC, kangz12345 commented on iquip/apps/monitor.py
> +        except:  # pylint: disable=bare-except
Please do not disable `bare-except`.

2024-04-02 05:29 UTC, BECATRUE commented on iquip/apps/monitor.py
> +        except:  # pylint: disable=bare-except
Okay. I will apply your review in #267.

2024-04-02 08:06 UTC, kangz12345 requested changes

2024-04-02 08:06 UTC, kangz12345 commented on iquip/apps/monitor.py
> +        except Exception:
Now you have to disable `broad-exception-caught` 😄

2024-04-03 08:54 UTC, kangz12345 approved these changes
LGTM

2024-04-03 09:05 UTC, merged