Aijuh/76/save logs to file
snu-quiqcl/iquip pull request #84
Opened 2023-07-28 07:58 UTC by Aijuh

### Added feature for saving logs to file. 
This PR closes issue #76 
Below are images of current loggerFrame and saved log format.

All logs are first saved at temp file by using file handler. I first think that level for fileHandler should be different for frameHandler. But since user chooses desired level, we can just save that level of logs to file. 

 When user presses `Save log to file` button, contents at temp file saved to log record file and temp file is cleared.
 When user presses `Clear log file` button, only log record file cleared.

The time format of logs in loggerFrame and file is different because we specify format for loggerFrame but use `%asctime` of format in fileHandler. 

All the details can be changed.  

![log_frame](https://github.com/snu-quiqcl/iquip/assets/43592775/520bf764-ce13-4a58-bc66-e70a31b7f8a1)
![file_log](https://github.com/snu-quiqcl/iquip/assets/43592775/15681d2b-ceb2-48db-9186-4e0662b57669)

2023-07-28 08:02 UTC, Aijuh commented
There is pylint error.
 I also tested pylint in my local, but it says `Too many instance attributes (8/7)` at `class LoggerApp(qiwis.BaseApp):`.
It seems there are 8 attributes in this file (7 classes and 1 logger), Should we delete one class or ignore this error message?

2023-07-30 06:48 UTC, BECATRUE requested changes

2023-07-30 06:48 UTC, BECATRUE commented on iquip/apps/logger.py
>      def __init__(self, name: str, parent: Optional[QObject] = None):
The constructor looks too long!
Please separate this into several methods.

2023-07-30 07:08 UTC, BECATRUE commented
I have several questions.

1. Handling the log file
I think it is natural to save logs to a file consistently in the background without clicking a button.
In addition, I think there are too many button in the `loggerFrame` so that it looks convoluted.
But, I wonder How @kangz12345 think of it.

2. Setting the handler level
Due to the same reason above, I think we should set the file logger level to DEBUG or INFO constantly.

2023-07-30 15:03 UTC, Aijuh commented
I am sorry that I didn't update quickly, but I should delete this PR and create new branch.
This PR's branch didn't stem from current branch. It stems from previous error-branch.
I will create new branch and new PR.

2023-07-30 15:07 UTC, closed without merging